### PR TITLE
Fixed links for contributing

### PR DESCRIPTION
**Pull request by klopfdreh**
Would you be so kind and give me access to the site, too. so that I can push directly to the asf-site branch of wicket-site, but not to do it via pull requests? Thanks! :smiley:

### CODE REVIEW

**Comment by martin-g** [comment]
You should be able to push to https://git-wip-us.apache.org/repos/asf/wicket-site.git

**Comment by martin-g** [comment]
This is just a mirror of it.

**Comment by klopfdreh** [comment]
Oh - I just had to know this. I configure the push right now. Thanks! :+1:

**Comment by klopfdreh** [comment]
Only hint for me, what to fix, too:

https://raw.githubusercontent.com/apache/wicket-site/asf-site/learn/books/index.md

``` html
<a href="paxisbuchwicket.html"> should be <a href="praxisbuchwicket.html">
```

**Comment by martin-g** [comment]
Check `readme.md` in the root ;-)

**Comment by klopfdreh** [comment]
What up with it? Something I missed? Or did you mixed the PRs by writing your last commt?

**Comment by martin-g** [comment]
The readme explains how to run Jekyll locally.
This helps you test your changes, and thus see what and where should be modified.
And also generates the final HTML files which are actually used by Apache pubsub system for the site.

**Comment by klopfdreh** [comment]
Thanks for the hint!

**Comment by klopfdreh** [comment]
I managed to get jerkyll running on mac os x 10.10.x - I just had to add some steps in the gem installation:

sudo gem uninstall cocoapods
sudo gem install xcodeproj
sudo gem install cocoapods
sudo gem install iconv -v "1.0.3"
sudo gem install jekyll

Maybe we can add this to the doc :smile: 

I pushed the fixes for the links to the asf-site branch and tested my changes before - working now!

**Comment by klopfdreh** [comment]
Hope they are reflected back soon - the two commits aren't available at the moment :question:

**Comment by martin-g** [comment]
> And also generates the final HTML files which are actually used by Apache pubsub system for the site.

^^

**Comment by martin-g** [comment]
You pushed just `.md` files. You need to push also the generated `.html`s

**Comment by klopfdreh** [comment]
Done, I added a separate commit with all generated html's

**Comment by martin-g** [comment]
:fireworks:

**Pull request closed without merging**
