### PR TITLE
Updated URL for Wicket Source & added Wicket Source NetBeans plugin

### PR DESCRIPTION
**Pull request by JoachimRohde**

### CODE REVIEW

**Comment by klopfdreh** [comment]
+1 to integrate. Is someone able to merge this - I am busy currenctly.

fyi @martin-g , @bitstorm

**Comment by martin-g** [comment]
Testing mail notifications!

**Comment by JoachimRohde** [comment]
@martin-g FYI: I received a notification mail

**Comment by martin-g** [comment]
Thanks for confirming, @JoachimRohde !
I did not. But now I did for your message.
Maybe GitHub doesn't notify the author of the message. I'll see what will happen with this message.

**Comment by martin-g** [comment]
Hah. I see what happens.
You received the notification personally because your are the PR creator.
I've received a notification about your message because you have mentioned me.
But dev@wicket.apache.org didn't receive any notification about any of the messages. https://issues.apache.org/jira/browse/INFRA-13078 is not really done, IMO.

**Pull request merged**
