### PR TITLE
Applied new information about Wicket 8.x

### PR DESCRIPTION
**Pull request by klopfdreh**
I added some comments, because there are some links broken by redirects / generation issues.

### CODE REVIEW

**Comment by martin-g** [comment]
> s.apache.org/wicket8migrate

It should be easy to create `http://s.apache.org/wicket8migrate2` or `http://s.apache.org/wicket8migration` that points to the correct location.

**Comment by martin-g** [comment]
> Javadocs also left ot be generated to:
> 
> http://ci.apache.org/projects/wicket/apidocs/8.x/index.html

The problem here is with Javadoc 8.

https://ci.apache.org/projects/wicket/apidocs/8.x/ has no index.html

I see the same even locally:

```
$ ls -la target/apidocs/                                                                                                                                               22:37:51 
total 16K
-rwxrwxr-x 1 martin martin   90 Oct  5 22:37 javadoc.sh*
-rw-rw-r-- 1 martin martin 1.3K Oct  5 22:37 options
drwxrwxr-x 3 martin martin 4.0K Oct  5 22:37 org/
-rw-rw-r-- 1 martin martin  800 Oct  5 22:37 packages
```

**Comment by martin-g** [comment]
The problem with javadoc is:

```
com.sun.tools.javac.code.Symbol$CompletionFailure: class file for org.hamcrest.Matcher not found
javadoc: error - com.sun.tools.javac.code.Symbol$CompletionFailure: class file for org.hamcrest.Matcher not found

Command line was: /home/martin/devel/jdk1.8.0_60/jre/../bin/javadoc -J-Xmx256m -J-Xms128m @options @packages

Refer to the generated Javadoc files in '/home/martin/git/apache/wicket/wicket-util/target/apidocs' dir.

    at org.apache.maven.plugin.javadoc.AbstractJavadocMojo.executeJavadocCommandLine(AbstractJavadocMojo.java:5163)
    at org.apache.maven.plugin.javadoc.AbstractJavadocMojo.executeReport(AbstractJavadocMojo.java:2075)
    at org.apache.maven.plugin.javadoc.JavadocJar.execute(JavadocJar.java:188)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
```

but I have no idea why it needs this class.

**Comment by klopfdreh** [comment]
> It should be easy to create http://s.apache.org/wicket8migrate2 or http://s.apache.org/wicket8migration > that points to the correct location.

Mh tried both and it is not working for me.

**Comment by martin-g** [comment]
http://s.apache.org/wicket8migration works fine now!

**Comment by klopfdreh** [comment]
done! :smile:

**Comment by klopfdreh** [comment]
The javadoc problem is really strange - can't find any solution for that at the moment. :fearful:

**Comment by martin-g** [comment]
I've fixed it with the change of scope for Hamcrest.

**Comment by klopfdreh** [comment]
Great! Thank you. Then only the decision about the servlet API / Jetty left.

**Comment by martin-g** [comment]
Cast your vote!

**Comment by klopfdreh** [comment]
Done!

**Comment by klopfdreh** [comment]
Can this PR be merged? (Also with the new Wicket 8 content)

**Comment by martin-g** [comment]
:+1:

**Comment by klopfdreh** [comment]
Integrated due to: https://github.com/apache/wicket-site/commit/3d662441dbf2997a0119aa2de668ca87071f8282 , https://github.com/apache/wicket-site/commit/8d79fca8c8e182bd5d4a3a889d720eea0f6b0eb0 , https://github.com/apache/wicket-site/commit/d091e12a8f08f71850383dbcd4a7830f830b0a86

**Pull request closed without merging**
