### PR TITLE
Adding a new Udemy course link to /learn page

### PR DESCRIPTION
**Pull request by dmarko484**
I have released a new Udemy course in english language named "Starting with Apache Wicket 9.x". I found an 'Online courses' section on your web site so please consider adding this link to existing one ...

thank you
David Marko

### CODE REVIEW

**Review by martin-g — APPROVED** [review]

**Comment by dmarko484** [comment]
Would be even possible to advertise a link on Apache Wicket twitter?

**Comment by martin-g** [comment]
I don't think this would be appropriate for a paid course. Sorry!

**Comment by bitstorm** [comment]
> I don't think this would be appropriate for a paid course. Sorry!
Actually, we were already listing 'Apache Wicket Kompakt', which is a paid course on Udemy as well. I don't think it violates any ASF rule (after all it is like linking a book), but we might emphasize that the courses we are linking are paid.

**Comment by martin-g** [comment]
@bitstorm My answer was about the advertisement on Twitter.

**Comment by dashorst** [comment]
I think that we could promote both courses on twitter using a link to the trainings page on our web site with an announcement "Two new Wicket 9.x trainings are available! Look here to learn more about them https://s.apache.org/wicketcourses".

**Comment by bitstorm** [comment]
@dashorst I like the idea! Do you think is against any ASF rule (I know it might be a one million dollars question :-) )?

**Comment by dashorst** [comment]
Not a lawyer nor a non-profit status specialist, but linking to any and all training on Wicket is for the greater good IMO. 🤷

**Pull request merged**
